  - name: Verify Ciphers option ciphers in openssh.config
    ansible.builtin.lineinfile:
      path: /etc/crypto-policies/back-ends/openssh.config
      create: true
      line: Ciphers aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes256-ctr,aes128-gcm@openssh.com,aes128-ctr
      regexp: ".*Ciphers.*"
      insertafter: Ciphers aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes256-ctr,aes128-gcm@openssh.com,aes128-ctr

